//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiGL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnes
    {
        public int IdPersonne { get; set; }
        public string NomPrenomPersonne { get; set; }
        public string AdressePersonne { get; set; }
        public string TelPersonne { get; set; }
        public string EmailPersonne { get; set; }
        public System.DateTime DateNaissancePersonne { get; set; }
    }
}
